version: '3'

services:
  simple-http:
    image: halverneus/static-file-server
    container_name: medusa-simple-http-dev
    ports:
      - 9090:8080
    volumes:
      - ./dev/gallery:/web

  postgresql:
    image: postgres:latest
    container_name: medusa-postgresql-dev
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medusa
      - POSTGRES_USER=medusa_user
      - POSTGRES_PASSWORD=medusa_pass
    ports:
      - 5432:5432
    
  pgadmin:
    image: adminer
    container_name: medusa-pgadmin-dev
    ports:
      - 9000:8080
    depends_on:
      - postgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=nope@nope.nop
      - PGADMIN_DEFAULT_PASSWORD=adminPass

volumes:
  postgresql:
