spring:
  application:
    name: medusa
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: medusa
    baselineOnMigrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    enabled: ${FLYWAY_ENABLED:true}
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/medusa?currentSchema=medusa}
    username: ${SPRING_DATASOURCE_USERNAME:medusa_user}
    password: ${SPRING_DATASOURCE_PASSWORD:medusa_pass}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:100MB}

server:
  port: ${SERVER_PORT:8080}
  cors:
    allowedOrigins: ${SERVER_CORS_ALLOWED_ORIGINS:http://localhost:5173}

filestorage:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}
  max-file-size: ${FILE_MAX_SIZE_BYTES:104857600}  # 100MB in bytes
  allowed-mime-types:
    - image/jpeg
    - image/png
    - image/gif
    - image/webp
    - image/bmp
    - video/mp4
    - video/webm
    - video/ogg
    - video/quicktime

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.randol.medusa: ${LOG_LEVEL_APP:DEBUG}
    org.springdoc: INFO
  pattern:
    # More detailed for file logging
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    # Simpler for console during development
    console: "%d{HH:mm:ss} %-5level - %msg%n"
  file:
    name: ${LOG_FILE_PATH:logs/medusa.log}
    max-size: ${LOG_MAX_SIZE:10MB}
    max-history: ${LOG_RETENTION_DAYS:7}

springdoc:
  packages-to-scan: org.randol.medusa.controllers